import {
  db,
  wilayasTable,
  categoriesTable,
  listingsTable,
  servicesTable,
  reviewsTable,
} from "@workspace/db";
import { sql } from "drizzle-orm";

async function seed() {
  const seedMode = process.env.SEED_MODE === "bootstrap" ? "bootstrap" : "reset";
  console.log(`Seeding database in ${seedMode} mode...`);

  if (seedMode === "bootstrap") {
    const existing = await db.select().from(listingsTable).limit(1);
    if (existing.length > 0) {
      console.log("Bootstrap seed skipped; listings already present");
      return;
    }
  }

  if (seedMode === "reset") {
    await db.execute(sql`TRUNCATE TABLE reviews, services, listings, categories, wilayas RESTART IDENTITY CASCADE`);
  }

  // Seed wilayas (all 58 Algerian provinces)
  const wilayaData = [
    { code: 1, name: "Adrar", nameAr: "أدرار", region: "Sud-Ouest" },
    { code: 2, name: "Chlef", nameAr: "الشلف", region: "Centre-Ouest" },
    { code: 3, name: "Laghouat", nameAr: "الأغواط", region: "Centre-Sud" },
    { code: 4, name: "Oum El Bouaghi", nameAr: "أم البواقي", region: "Est" },
    { code: 5, name: "Batna", nameAr: "باتنة", region: "Est" },
    { code: 6, name: "Béjaïa", nameAr: "بجاية", region: "Centre-Est" },
    { code: 7, name: "Biskra", nameAr: "بسكرة", region: "Centre-Sud" },
    { code: 8, name: "Béchar", nameAr: "بشار", region: "Sud-Ouest" },
    { code: 9, name: "Blida", nameAr: "البليدة", region: "Centre" },
    { code: 10, name: "Bouira", nameAr: "البويرة", region: "Centre" },
    { code: 11, name: "Tamanrasset", nameAr: "تمنراست", region: "Grand Sud" },
    { code: 12, name: "Tébessa", nameAr: "تبسة", region: "Est" },
    { code: 13, name: "Tlemcen", nameAr: "تلمسان", region: "Ouest" },
    { code: 14, name: "Tiaret", nameAr: "تيارت", region: "Centre-Ouest" },
    { code: 15, name: "Tizi Ouzou", nameAr: "تيزي وزو", region: "Centre-Est" },
    { code: 16, name: "Alger", nameAr: "الجزائر", region: "Centre" },
    { code: 17, name: "Djelfa", nameAr: "الجلفة", region: "Centre-Sud" },
    { code: 18, name: "Jijel", nameAr: "جيجل", region: "Est" },
    { code: 19, name: "Sétif", nameAr: "سطيف", region: "Est" },
    { code: 20, name: "Saïda", nameAr: "سعيدة", region: "Ouest" },
    { code: 21, name: "Skikda", nameAr: "سكيكدة", region: "Est" },
    { code: 22, name: "Sidi Bel Abbès", nameAr: "سيدي بلعباس", region: "Ouest" },
    { code: 23, name: "Annaba", nameAr: "عنابة", region: "Est" },
    { code: 24, name: "Guelma", nameAr: "قالمة", region: "Est" },
    { code: 25, name: "Constantine", nameAr: "قسنطينة", region: "Est" },
    { code: 26, name: "Médéa", nameAr: "المدية", region: "Centre" },
    { code: 27, name: "Mostaganem", nameAr: "مستغانم", region: "Ouest" },
    { code: 28, name: "M'Sila", nameAr: "المسيلة", region: "Centre-Est" },
    { code: 29, name: "Mascara", nameAr: "معسكر", region: "Ouest" },
    { code: 30, name: "Ouargla", nameAr: "ورقلة", region: "Sud-Est" },
    { code: 31, name: "Oran", nameAr: "وهران", region: "Ouest" },
    { code: 32, name: "El Bayadh", nameAr: "البيض", region: "Sud-Ouest" },
    { code: 33, name: "Illizi", nameAr: "إليزي", region: "Grand Sud" },
    { code: 34, name: "Bordj Bou Arréridj", nameAr: "برج بوعريريج", region: "Centre-Est" },
    { code: 35, name: "Boumerdès", nameAr: "بومرداس", region: "Centre" },
    { code: 36, name: "El Tarf", nameAr: "الطارف", region: "Est" },
    { code: 37, name: "Tindouf", nameAr: "تندوف", region: "Grand Sud" },
    { code: 38, name: "Tissemsilt", nameAr: "تيسمسيلت", region: "Centre-Ouest" },
    { code: 39, name: "El Oued", nameAr: "الوادي", region: "Sud-Est" },
    { code: 40, name: "Khenchela", nameAr: "خنشلة", region: "Est" },
    { code: 41, name: "Souk Ahras", nameAr: "سوق أهراس", region: "Est" },
    { code: 42, name: "Tipaza", nameAr: "تيبازة", region: "Centre" },
    { code: 43, name: "Mila", nameAr: "ميلة", region: "Est" },
    { code: 44, name: "Aïn Defla", nameAr: "عين الدفلى", region: "Centre-Ouest" },
    { code: 45, name: "Naâma", nameAr: "النعامة", region: "Sud-Ouest" },
    { code: 46, name: "Aïn Témouchent", nameAr: "عين تيموشنت", region: "Ouest" },
    { code: 47, name: "Ghardaïa", nameAr: "غرداية", region: "Sud" },
    { code: 48, name: "Relizane", nameAr: "غليزان", region: "Centre-Ouest" },
    { code: 49, name: "Timimoun", nameAr: "تيميمون", region: "Sud-Ouest" },
    { code: 50, name: "Bordj Badji Mokhtar", nameAr: "برج باجي مختار", region: "Grand Sud" },
    { code: 51, name: "Ouled Djellal", nameAr: "أولاد جلال", region: "Centre-Sud" },
    { code: 52, name: "Béni Abbès", nameAr: "بني عباس", region: "Sud-Ouest" },
    { code: 53, name: "In Salah", nameAr: "عين صالح", region: "Grand Sud" },
    { code: 54, name: "In Guezzam", nameAr: "عين قزام", region: "Grand Sud" },
    { code: 55, name: "Touggourt", nameAr: "تقرت", region: "Sud-Est" },
    { code: 56, name: "Djanet", nameAr: "جانت", region: "Grand Sud" },
    { code: 57, name: "El M'Ghair", nameAr: "المغير", region: "Sud-Est" },
    { code: 58, name: "El Meniaa", nameAr: "المنيعة", region: "Grand Sud" },
  ];

  const wilayas = await db.insert(wilayasTable).values(wilayaData).returning();
  console.log(`✓ Seeded ${wilayas.length} wilayas`);

  const wilayaMap = Object.fromEntries(wilayas.map((w) => [w.code, w.id]));

  // Seed categories
  const categoryData = [
    {
      slug: "salons-coiffure",
      name: "Hair Salons",
      nameAr: "صالونات الحلاقة",
      nameFr: "Salons de Coiffure",
      icon: "✂️",
      description: "Professional hair salons and barbers for all hair types",
    },
    {
      slug: "spas-hammams",
      name: "Spas & Hammams",
      nameAr: "السبا والحمامات",
      nameFr: "Spas & Hammams",
      icon: "🛁",
      description: "Traditional Algerian hammams and modern wellness spas",
    },
    {
      slug: "cliniques-esthetiques",
      name: "Aesthetic Clinics",
      nameAr: "عيادات التجميل",
      nameFr: "Cliniques Esthétiques",
      icon: "💆",
      description: "Medical aesthetic treatments and cosmetic procedures",
    },
    {
      slug: "pharmacies",
      name: "Pharmacies",
      nameAr: "الصيدليات",
      nameFr: "Pharmacies",
      icon: "💊",
      description: "Pharmacies and health product stores",
    },
    {
      slug: "parfumeries",
      name: "Perfumeries",
      nameAr: "محلات العطور",
      nameFr: "Parfumeries",
      icon: "🌸",
      description: "Perfume shops and fragrance boutiques",
    },
    {
      slug: "soins-corps",
      name: "Body Care",
      nameAr: "العناية بالجسم",
      nameFr: "Soins du Corps",
      icon: "🧴",
      description: "Massage, body treatments and wellness centers",
    },
    {
      slug: "centres-dentaires",
      name: "Dental Centers",
      nameAr: "مراكز طب الأسنان",
      nameFr: "Centres Dentaires",
      icon: "🦷",
      description: "Dental clinics, orthodontics and oral health care",
    },
    {
      slug: "opticiens",
      name: "Opticians",
      nameAr: "مراكز البصريات",
      nameFr: "Opticiens",
      icon: "👁️",
      description: "Eye care centers and optical stores",
    },
    {
      slug: "nail-studios",
      name: "Nail Studios",
      nameAr: "صالونات الأظافر",
      nameFr: "Studios d'Ongles",
      icon: "💅",
      description: "Nail care, manicure and pedicure studios",
    },
    {
      slug: "centres-laser",
      name: "Laser Centers",
      nameAr: "مراكز الليزر",
      nameFr: "Centres Laser",
      icon: "⚡",
      description: "Laser hair removal and skin treatment centers",
    },
  ];

  const categories = await db.insert(categoriesTable).values(categoryData).returning();
  console.log(`✓ Seeded ${categories.length} categories`);

  const catMap = Object.fromEntries(categories.map((c) => [c.slug, c.id]));

  // Seed listings with rich data
  const listingData = [
    // Alger (16) - Hair Salons
    {
      name: "Salon Nour Beauté",
      slug: "salon-nour-beaute-alger",
      categoryId: catMap["salons-coiffure"],
      wilayaId: wilayaMap[16],
      address: "Rue Didouche Mourad, Alger Centre",
      phone: "+213 21 63 45 12",
      email: "nourbeaute@gmail.com",
      website: "https://salonnour.dz",
      description: "Salon de coiffure haut de gamme au cœur d'Alger. Spécialisé en coiffure feminine, colorations et soins capillaires. Notre équipe de professionnels vous accueille dans un cadre élégant et chaleureux.",
      rating: 4.8,
      reviewCount: 127,
      priceRange: "premium",
      coverImage: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800",
      images: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800", "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800"],
      tags: ["Coiffure femme", "Coloration", "Soins kératine", "Mariage"],
      featured: true,
      verified: true,
      openingHours: "Lun-Sam 9h-20h, Dim 10h-18h",
      latitude: 36.7538,
      longitude: 3.0588,
    },
    {
      name: "Barber Shop El Amir",
      slug: "barber-shop-el-amir-alger",
      categoryId: catMap["salons-coiffure"],
      wilayaId: wilayaMap[16],
      address: "Boulevard Mohamed V, Alger",
      phone: "+213 21 74 22 88",
      email: null,
      website: null,
      description: "Barbier traditionnel et moderne. Coupe homme, rasage traditionnel, barbe et soins. Ambiance authentique et service de qualité. Le lieu de rendez-vous des hommes d'Alger.",
      rating: 4.6,
      reviewCount: 89,
      priceRange: "moderate",
      coverImage: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800",
      images: ["https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=800"],
      tags: ["Coiffure homme", "Rasage", "Barbe", "Coupe classique"],
      featured: false,
      verified: true,
      openingHours: "Lun-Dim 8h-21h",
    },
    // Alger - Spas & Hammams
    {
      name: "Hammam Zita Luxe",
      slug: "hammam-zita-luxe-alger",
      categoryId: catMap["spas-hammams"],
      wilayaId: wilayaMap[16],
      address: "Hydra, Alger",
      phone: "+213 21 69 13 44",
      email: "hammamzita@gmail.com",
      website: null,
      description: "Hammam traditionnel algérien revisité dans un cadre luxueux. Profitez de notre savon beldi, gommage au kessa, masques au ghassoul et massages relaxants. Une expérience de bien-être authentique et raffinée.",
      rating: 4.9,
      reviewCount: 203,
      priceRange: "luxury",
      coverImage: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800",
      images: ["https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800", "https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800"],
      tags: ["Hammam", "Gommage", "Massages", "Ghassoul", "Savon beldi"],
      featured: true,
      verified: true,
      openingHours: "Lun-Dim 9h-22h",
      latitude: 36.7340,
      longitude: 3.0414,
    },
    {
      name: "Spa Wellness Beni Messous",
      slug: "spa-wellness-beni-messous",
      categoryId: catMap["spas-hammams"],
      wilayaId: wilayaMap[16],
      address: "Beni Messous, Alger",
      phone: "+213 23 45 67 89",
      email: "spa.wellness.bm@gmail.com",
      website: "https://spawellness.dz",
      description: "Centre de bien-être moderne offrant une gamme complète de soins: hammam, sauna, jacuzzi, massages thérapeutiques et soins esthétiques. Notre équipe de thérapeutes certifiés vous guide vers une relaxation totale.",
      rating: 4.5,
      reviewCount: 145,
      priceRange: "premium",
      coverImage: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
      images: ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800"],
      tags: ["Spa", "Sauna", "Jacuzzi", "Massages", "Soins visage"],
      featured: true,
      verified: true,
      openingHours: "Lun-Sam 10h-22h, Dim 10h-20h",
    },
    // Alger - Aesthetic Clinics
    {
      name: "Clinique Esthétique Dr. Sonia",
      slug: "clinique-esthetique-dr-sonia-alger",
      categoryId: catMap["cliniques-esthetiques"],
      wilayaId: wilayaMap[16],
      address: "Chéraga, Alger",
      phone: "+213 21 36 78 90",
      email: "drsonia.clinic@gmail.com",
      website: "https://drsonia-clinic.dz",
      description: "Clinique médicale esthétique dirigée par le Dr. Sonia Benali, dermatologue spécialisée en médecine esthétique. Traitements au laser, injections Botox, acide hyaluronique, peelings chimiques et soins anti-âge.",
      rating: 4.7,
      reviewCount: 178,
      priceRange: "luxury",
      coverImage: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800",
      images: ["https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800"],
      tags: ["Botox", "Acide hyaluronique", "Laser", "Peeling", "Anti-âge"],
      featured: true,
      verified: true,
      openingHours: "Lun-Ven 9h-18h, Sam 9h-14h",
    },
    // Oran (31) - Multiple categories
    {
      name: "Institut Beauté Wahrana",
      slug: "institut-beaute-wahrana-oran",
      categoryId: catMap["salons-coiffure"],
      wilayaId: wilayaMap[31],
      address: "Rue Larbi Ben M'hidi, Oran",
      phone: "+213 41 33 22 11",
      email: "wahrana.beaute@gmail.com",
      website: null,
      description: "Institut de beauté complet au cœur d'Oran. Coiffure, maquillage, soins du visage et du corps. Notre équipe talentueuse vous propose des prestations de qualité pour chaque occasion.",
      rating: 4.5,
      reviewCount: 94,
      priceRange: "moderate",
      coverImage: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800",
      images: ["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"],
      tags: ["Coiffure", "Maquillage", "Soins visage", "Mariage"],
      featured: true,
      verified: true,
      openingHours: "Lun-Sam 9h-20h",
    },
    {
      name: "Hammam Sidi El Houari",
      slug: "hammam-sidi-el-houari-oran",
      categoryId: catMap["spas-hammams"],
      wilayaId: wilayaMap[31],
      address: "Quartier Sidi El Houari, Oran",
      phone: "+213 41 44 55 66",
      email: null,
      website: null,
      description: "Hammam traditionnel dans le quartier historique de Sidi El Houari. Gommage, savon beldi, massages relaxants dans une ambiance authentique. Séparés hommes et femmes.",
      rating: 4.3,
      reviewCount: 67,
      priceRange: "budget",
      coverImage: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800",
      images: [],
      tags: ["Hammam traditionnel", "Gommage", "Savon beldi"],
      featured: false,
      verified: true,
      openingHours: "Lun-Dim 7h-22h",
    },
    {
      name: "Pharmacie El Andalous",
      slug: "pharmacie-el-andalous-oran",
      categoryId: catMap["pharmacies"],
      wilayaId: wilayaMap[31],
      address: "Boulevard Millénium, Oran",
      phone: "+213 41 55 77 88",
      email: "pharmacie.andalous@gmail.com",
      website: null,
      description: "Grande pharmacie moderne avec un large stock de médicaments, produits dermatologiques, cosmétiques et compléments alimentaires. Service de garde disponible. Conseil pharmaceutique professionnel.",
      rating: 4.4,
      reviewCount: 52,
      priceRange: "moderate",
      coverImage: "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800",
      images: [],
      tags: ["Pharmacie", "Dermatologie", "Cosmétiques", "Garde"],
      featured: false,
      verified: true,
      openingHours: "Lun-Sam 8h-22h, Dim 9h-18h",
    },
    // Constantine (25)
    {
      name: "Salon Firdaws",
      slug: "salon-firdaws-constantine",
      categoryId: catMap["salons-coiffure"],
      wilayaId: wilayaMap[25],
      address: "Rue Larbi Ben M'hidi, Constantine",
      phone: "+213 31 92 34 56",
      email: "salon.firdaws@gmail.com",
      website: null,
      description: "Salon de beauté et de coiffure à Constantine. Spécialisé en coiffure orientale, tresses, extensions cheveux et maquillage de mariage. Accueil chaleureux et service personnalisé.",
      rating: 4.6,
      reviewCount: 83,
      priceRange: "moderate",
      coverImage: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800",
      images: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800"],
      tags: ["Coiffure orientale", "Tresses", "Extensions", "Mariage"],
      featured: true,
      verified: true,
      openingHours: "Lun-Sam 9h-20h",
    },
    {
      name: "Centre Dentaire Dr. Hamza",
      slug: "centre-dentaire-dr-hamza-constantine",
      categoryId: catMap["centres-dentaires"],
      wilayaId: wilayaMap[25],
      address: "Rue 8 Mai 1945, Constantine",
      phone: "+213 31 64 22 90",
      email: "dr.hamza.dentiste@gmail.com",
      website: null,
      description: "Cabinet dentaire moderne équipé des dernières technologies. Soins dentaires complets: détartrage, caries, couronne, blanchiment, orthodontie et implants. Dr. Hamza Boudjelthia, 15 ans d'expérience.",
      rating: 4.7,
      reviewCount: 112,
      priceRange: "moderate",
      coverImage: "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=800",
      images: [],
      tags: ["Dentiste", "Blanchiment", "Orthodontie", "Implants"],
      featured: false,
      verified: true,
      openingHours: "Lun-Ven 8h-18h, Sam 8h-14h",
    },
    // Annaba (23)
    {
      name: "Beauty World Annaba",
      slug: "beauty-world-annaba",
      categoryId: catMap["parfumeries"],
      wilayaId: wilayaMap[23],
      address: "Boulevard de la République, Annaba",
      phone: "+213 38 84 33 22",
      email: "beautyworld.annaba@gmail.com",
      website: null,
      description: "Boutique de parfums et cosmétiques de prestige. Large sélection de parfums français, arabes et orientaux. Produits de maquillage, soins et accessoires beauté. Conseillères beauté qualifiées.",
      rating: 4.5,
      reviewCount: 76,
      priceRange: "premium",
      coverImage: "https://images.unsplash.com/photo-1541643600914-78b084683702?w=800",
      images: ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800"],
      tags: ["Parfums", "Cosmétiques", "Maquillage", "Soins"],
      featured: true,
      verified: true,
      openingHours: "Lun-Sam 9h-21h, Dim 10h-19h",
    },
    // Sétif (19)
    {
      name: "Laser Center Sétif",
      slug: "laser-center-setif",
      categoryId: catMap["centres-laser"],
      wilayaId: wilayaMap[19],
      address: "Rue 8 Mai 1945, Sétif",
      phone: "+213 36 84 56 78",
      email: "lasercenter.setif@gmail.com",
      website: "https://lasersetif.dz",
      description: "Centre spécialisé en épilation laser définitive et soins de la peau par laser. Appareils certifiés médicalement, résultats garantis. Traitements: épilation, détatouage, rajeunissement cutané, taches pigmentaires.",
      rating: 4.6,
      reviewCount: 134,
      priceRange: "premium",
      coverImage: "https://images.unsplash.com/photo-1516585427167-9f4af9627e6c?w=800",
      images: [],
      tags: ["Épilation laser", "Détatouage", "Soins peau", "Taches"],
      featured: true,
      verified: true,
      openingHours: "Lun-Sam 9h-19h",
    },
    // Tizi Ouzou (15)
    {
      name: "Nail Studio Kabyle",
      slug: "nail-studio-kabyle-tizi-ouzou",
      categoryId: catMap["nail-studios"],
      wilayaId: wilayaMap[15],
      address: "Avenue Abane Ramdane, Tizi Ouzou",
      phone: "+213 26 21 33 45",
      email: null,
      website: null,
      description: "Studio spécialisé en nail art, manucure et pédicure. Gel, résine, acrylique, vernis semi-permanent. Designs traditionnels berbères et modernes. Matériel stérilisé pour votre sécurité.",
      rating: 4.4,
      reviewCount: 58,
      priceRange: "moderate",
      coverImage: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800",
      images: ["https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=800"],
      tags: ["Nail art", "Manucure", "Pédicure", "Gel", "Semi-permanent"],
      featured: false,
      verified: true,
      openingHours: "Mar-Sam 9h-19h",
    },
    // Blida (9)
    {
      name: "Optique Lumière",
      slug: "optique-lumiere-blida",
      categoryId: catMap["opticiens"],
      wilayaId: wilayaMap[9],
      address: "Centre Commercial Atlas, Blida",
      phone: "+213 25 49 66 77",
      email: "optique.lumiere@gmail.com",
      website: null,
      description: "Centre optique complet avec examen de vue gratuit. Lunettes de vue et solaires des meilleures marques. Lentilles de contact. Montures pour enfants et adultes. Service rapide: verres prêts en 1 heure.",
      rating: 4.3,
      reviewCount: 44,
      priceRange: "moderate",
      coverImage: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=800",
      images: [],
      tags: ["Optique", "Lunettes", "Lentilles", "Examen de vue"],
      featured: false,
      verified: true,
      openingHours: "Lun-Sam 8h30-20h",
    },
    // Béjaïa (6)
    {
      name: "Centre de Soins Corporels Yemma",
      slug: "centre-soins-corporels-yemma-bejaia",
      categoryId: catMap["soins-corps"],
      wilayaId: wilayaMap[6],
      address: "Rue des Aures, Béjaïa",
      phone: "+213 34 21 56 89",
      email: "yemma.soins@gmail.com",
      website: null,
      description: "Centre de bien-être et de soins corporels traditionnel berbère. Massages, soins du corps aux huiles essentielles, enveloppements d'argile, drainage lymphatique. Techniques ancestrales et modernes.",
      rating: 4.7,
      reviewCount: 91,
      priceRange: "moderate",
      coverImage: "https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800",
      images: ["https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800"],
      tags: ["Massages", "Soins corps", "Argile", "Drainage", "Huiles essentielles"],
      featured: true,
      verified: true,
      openingHours: "Lun-Sam 9h-20h",
    },
    // Tlemcen (13)
    {
      name: "Salon Oriental Tlemcen",
      slug: "salon-oriental-tlemcen",
      categoryId: catMap["salons-coiffure"],
      wilayaId: wilayaMap[13],
      address: "Médina de Tlemcen",
      phone: "+213 43 26 88 90",
      email: null,
      website: null,
      description: "Salon de beauté andalous dans la médina de Tlemcen. Henna traditionnelle, coiffure mariage, maquillage oriental. Perpétue les traditions de beauté de la cité des Zianides depuis 1985.",
      rating: 4.8,
      reviewCount: 156,
      priceRange: "moderate",
      coverImage: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800",
      images: ["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"],
      tags: ["Henna", "Coiffure mariage", "Maquillage oriental", "Tradition"],
      featured: true,
      verified: true,
      openingHours: "Lun-Sam 9h-20h, Dim 10h-16h",
    },
    // Batna (5)
    {
      name: "Clinique Dentaire El Aures",
      slug: "clinique-dentaire-el-aures-batna",
      categoryId: catMap["centres-dentaires"],
      wilayaId: wilayaMap[5],
      address: "Rue Amirouche, Batna",
      phone: "+213 33 87 12 34",
      email: "clinique.aures@gmail.com",
      website: null,
      description: "Clinique dentaire moderne équipée de la technologie numérique. Radiographie 3D, chirurgie implantaire, prothèses sur mesure, orthodontie invisible. Une équipe de 4 praticiens qualifiés à votre service.",
      rating: 4.5,
      reviewCount: 88,
      priceRange: "premium",
      coverImage: "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=800",
      images: [],
      tags: ["Dentiste", "Implants", "Orthodontie", "Radiographie 3D"],
      featured: false,
      verified: true,
      openingHours: "Lun-Ven 8h-18h",
    },
    // Second listing Alger - nail
    {
      name: "Studio Ongles Prestige",
      slug: "studio-ongles-prestige-alger",
      categoryId: catMap["nail-studios"],
      wilayaId: wilayaMap[16],
      address: "Dely Ibrahim, Alger",
      phone: "+213 23 45 67 11",
      email: "studio.prestige@gmail.com",
      website: null,
      description: "Studio d'ongles haut de gamme spécialisé en nail art de luxe. Gel, acrylique, pose de capsules, nail art 3D, French manucure et pédicure soins. Produits importés de haute qualité.",
      rating: 4.9,
      reviewCount: 213,
      priceRange: "premium",
      coverImage: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800",
      images: ["https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=800"],
      tags: ["Nail art", "Gel", "Acrylique", "French manucure", "3D"],
      featured: true,
      verified: true,
      openingHours: "Mar-Dim 10h-20h",
    },
    // Ouargla (30)
    {
      name: "Pharmacie Centrale Ouargla",
      slug: "pharmacie-centrale-ouargla",
      categoryId: catMap["pharmacies"],
      wilayaId: wilayaMap[30],
      address: "Place du 1er Novembre, Ouargla",
      phone: "+213 29 70 23 45",
      email: null,
      website: null,
      description: "Pharmacie principale d'Ouargla avec un large stock. Médicaments, produits parapharmaceutiques, cosmétiques naturels du Sahara. Service de garde permanent. Livraison à domicile disponible.",
      rating: 4.2,
      reviewCount: 31,
      priceRange: "moderate",
      coverImage: "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800",
      images: [],
      tags: ["Pharmacie", "Garde", "Parapharmacie", "Livraison"],
      featured: false,
      verified: true,
      openingHours: "24h/24, 7j/7",
    },
    // Alger - Parfumerie
    {
      name: "Parfumerie Diaf",
      slug: "parfumerie-diaf-alger",
      categoryId: catMap["parfumeries"],
      wilayaId: wilayaMap[16],
      address: "Rue Didouche Mourad, Alger",
      phone: "+213 21 74 89 33",
      email: "parfumerie.diaf@gmail.com",
      website: "https://parfumdiaf.dz",
      description: "La parfumerie incontournable d'Alger depuis 1995. Parfums originaux français, orientaux et arabes. Ouds précieux, musc blanc, ambre. Plus de 2000 références disponibles en boutique. Vente en gros et détail.",
      rating: 4.6,
      reviewCount: 167,
      priceRange: "premium",
      coverImage: "https://images.unsplash.com/photo-1541643600914-78b084683702?w=800",
      images: ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800"],
      tags: ["Parfums originaux", "Oud", "Musc", "Oriental", "Gros"],
      featured: true,
      verified: true,
      openingHours: "Lun-Sam 9h-22h, Dim 10h-20h",
    },
    // Alger - Opticien
    {
      name: "Optique Lumina Hydra",
      slug: "optique-lumina-hydra-alger",
      categoryId: catMap["opticiens"],
      wilayaId: wilayaMap[16],
      address: "Centre Commercial Riad, Hydra, Alger",
      phone: "+213 21 60 44 55",
      email: "lumina.optique@gmail.com",
      website: "https://lumina-optique.dz",
      description: "Centre optique premium à Hydra. Examen complet de la vue par opticien diplômé. Montures de créateurs: Oakley, Ray-Ban, Gucci, Prada. Lentilles progressives, anti-lumière bleue. Service livraison à domicile.",
      rating: 4.7,
      reviewCount: 99,
      priceRange: "premium",
      coverImage: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=800",
      images: [],
      tags: ["Lunettes designer", "Examen vue", "Lentilles", "Anti-lumière bleue"],
      featured: false,
      verified: true,
      openingHours: "Lun-Sam 9h-21h",
    },
    // Mostaganem (27)
    {
      name: "Institut Charme Mostaganem",
      slug: "institut-charme-mostaganem",
      categoryId: catMap["soins-corps"],
      wilayaId: wilayaMap[27],
      address: "Quartier El Arsa, Mostaganem",
      phone: "+213 45 26 77 88",
      email: null,
      website: null,
      description: "Institut de beauté et de soins corporels complet. Épilation, soins du visage, massages relaxants, bains de boue. Spécialité: soins marins aux algues de Mostaganem. Service exclusif et personnalisé.",
      rating: 4.4,
      reviewCount: 63,
      priceRange: "moderate",
      coverImage: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800",
      images: [],
      tags: ["Épilation", "Soins visage", "Massages", "Soins marins"],
      featured: false,
      verified: true,
      openingHours: "Lun-Sam 9h-19h",
    },
  ];

  const listings = await db.insert(listingsTable).values(listingData).returning();
  console.log(`✓ Seeded ${listings.length} listings`);

  const listingMap = Object.fromEntries(listings.map((l) => [l.slug, l.id]));

  // Seed services
  const servicesData = [
    // Salon Nour Beauté
    { listingId: listingMap["salon-nour-beaute-alger"], name: "Coupe + Brushing", nameAr: "قص + تمليس", price: 1500, priceMax: 3000, duration: "1h-1h30" },
    { listingId: listingMap["salon-nour-beaute-alger"], name: "Coloration complète", nameAr: "صبغة كاملة", price: 4000, priceMax: 8000, duration: "2h-3h" },
    { listingId: listingMap["salon-nour-beaute-alger"], name: "Soin kératine brésilien", nameAr: "علاج الكيراتين البرازيلي", price: 8000, priceMax: 15000, duration: "3h-4h" },
    { listingId: listingMap["salon-nour-beaute-alger"], name: "Coiffure mariage", nameAr: "تسريحة العروس", price: 5000, priceMax: 12000, duration: "2h-3h" },
    { listingId: listingMap["salon-nour-beaute-alger"], name: "Lissage permanent", nameAr: "تمليس دائم", price: 10000, priceMax: 20000, duration: "3h-5h" },

    // Barber El Amir
    { listingId: listingMap["barber-shop-el-amir-alger"], name: "Coupe homme", nameAr: "قصة رجال", price: 400, priceMax: 600, duration: "30min" },
    { listingId: listingMap["barber-shop-el-amir-alger"], name: "Rasage traditionnel", nameAr: "حلاقة تقليدية", price: 300, priceMax: 500, duration: "30min" },
    { listingId: listingMap["barber-shop-el-amir-alger"], name: "Coupe + Barbe", nameAr: "قصة + لحية", price: 700, priceMax: 900, duration: "1h" },

    // Hammam Zita
    { listingId: listingMap["hammam-zita-luxe-alger"], name: "Hammam complet", nameAr: "حمام كامل", price: 2500, priceMax: 4000, duration: "1h30" },
    { listingId: listingMap["hammam-zita-luxe-alger"], name: "Gommage au kessa", nameAr: "تقشير بالكيس", price: 1000, priceMax: 1500, duration: "45min" },
    { listingId: listingMap["hammam-zita-luxe-alger"], name: "Masque ghassoul", nameAr: "قناع الغاسول", price: 800, priceMax: 1200, duration: "30min" },
    { listingId: listingMap["hammam-zita-luxe-alger"], name: "Massage relaxant", nameAr: "تدليك استرخاء", price: 2000, priceMax: 3000, duration: "1h" },
    { listingId: listingMap["hammam-zita-luxe-alger"], name: "Forfait spa complet", nameAr: "باقة سبا كاملة", price: 5000, priceMax: 8000, duration: "3h" },

    // Clinique Dr. Sonia
    { listingId: listingMap["clinique-esthetique-dr-sonia-alger"], name: "Injection Botox", nameAr: "حقن البوتوكس", price: 15000, priceMax: 30000, duration: "30min" },
    { listingId: listingMap["clinique-esthetique-dr-sonia-alger"], name: "Acide hyaluronique", nameAr: "حمض الهيالورونيك", price: 20000, priceMax: 40000, duration: "45min" },
    { listingId: listingMap["clinique-esthetique-dr-sonia-alger"], name: "Peeling chimique", nameAr: "التقشير الكيميائي", price: 8000, priceMax: 15000, duration: "1h" },
    { listingId: listingMap["clinique-esthetique-dr-sonia-alger"], name: "Laser CO2", nameAr: "ليزر CO2", price: 25000, priceMax: 50000, duration: "1h-2h" },

    // Laser Center Sétif
    { listingId: listingMap["laser-center-setif"], name: "Épilation laser jambes complètes", nameAr: "إزالة الشعر بالليزر للساقين", price: 8000, priceMax: 12000, duration: "1h-1h30" },
    { listingId: listingMap["laser-center-setif"], name: "Épilation laser maillot", nameAr: "إزالة الشعر بالليزر للبيكيني", price: 5000, priceMax: 8000, duration: "45min" },
    { listingId: listingMap["laser-center-setif"], name: "Séance taches pigmentaires", nameAr: "جلسة تفتيح البقع الجلدية", price: 6000, priceMax: 10000, duration: "30min" },

    // Studio ongles prestige
    { listingId: listingMap["studio-ongles-prestige-alger"], name: "Pose gel complète", nameAr: "وضع الجل", price: 2000, priceMax: 3500, duration: "1h30" },
    { listingId: listingMap["studio-ongles-prestige-alger"], name: "Nail art personnalisé", nameAr: "رسم الأظافر", price: 500, priceMax: 2000, duration: "variable" },
    { listingId: listingMap["studio-ongles-prestige-alger"], name: "Manucure + vernis semi", nameAr: "مانيكير + ورنيش", price: 1200, priceMax: 1800, duration: "1h" },
    { listingId: listingMap["studio-ongles-prestige-alger"], name: "Pédicure soins", nameAr: "باديكور علاجي", price: 1500, priceMax: 2500, duration: "1h30" },
  ];

  await db.insert(servicesTable).values(servicesData);
  console.log(`✓ Seeded ${servicesData.length} services`);

  // Seed reviews
  const reviewsData = [
    { listingId: listingMap["salon-nour-beaute-alger"], authorName: "Amira Benali", rating: 5, comment: "Excellent salon! L'équipe est professionnelle et le résultat est magnifique. Ma coloration est parfaite. Je recommande vivement!" },
    { listingId: listingMap["salon-nour-beaute-alger"], authorName: "Fatima Khelili", rating: 5, comment: "Soin kératine extraordinaire, mes cheveux sont comme de la soie. Staff très accueillant. Prix justifié par la qualité." },
    { listingId: listingMap["salon-nour-beaute-alger"], authorName: "Samira Mansouri", rating: 4, comment: "Très bon salon, je suis venue pour ma coiffure de mariage et j'étais ravie. Seul bémol: l'attente un peu longue." },
    { listingId: listingMap["salon-nour-beaute-alger"], authorName: "Nadia Boudiaf", rating: 5, comment: "Le meilleur salon d'Alger! Je viens ici depuis 5 ans et je n'ai jamais été déçue. Très professionnel." },

    { listingId: listingMap["hammam-zita-luxe-alger"], authorName: "Yasmine Aït Ahmed", rating: 5, comment: "Une expérience magnifique! Le hammam est propre, luxueux et le personnel est aux petits soins. Le gommage était excellent." },
    { listingId: listingMap["hammam-zita-luxe-alger"], authorName: "Leila Cherif", rating: 5, comment: "Je viens ici tous les mois. Le massage avec l'huile d'argan est divin. Meilleur hammam d'Alger sans hésitation!" },
    { listingId: listingMap["hammam-zita-luxe-alger"], authorName: "Rania Messaoudi", rating: 5, comment: "Parfait pour se détendre. L'atmosphère est apaisante, les soins sont de qualité et les prix sont raisonnables pour le luxe offert." },

    { listingId: listingMap["clinique-esthetique-dr-sonia-alger"], authorName: "Sara Boudjelthia", rating: 5, comment: "Dr. Sonia est une experte. Mon traitement Botox est naturel et discret. Très professionnel et hygiénique." },
    { listingId: listingMap["clinique-esthetique-dr-sonia-alger"], authorName: "Houria Lazreg", rating: 4, comment: "Très bonne clinique. Les résultats du peeling sont visibles rapidement. Toujours un peu cher mais la qualité est là." },

    { listingId: listingMap["salon-firdaws-constantine"], authorName: "Chahra Benmansour", rating: 5, comment: "La meilleure pour la coiffure orientale à Constantine! Ma tresse mariage était sublime. Merci!" },
    { listingId: listingMap["salon-firdaws-constantine"], authorName: "Djamila Hamidi", rating: 4, comment: "Très bon salon, personnel sympa. La henna était magnifique mais il faut réserver à l'avance." },

    { listingId: listingMap["hammam-sidi-el-houari-oran"], authorName: "Zineb Belarbi", rating: 4, comment: "Hammam typique oranais, authentique et propre. Prix très abordable. Gommage efficace!" },
    { listingId: listingMap["hammam-sidi-el-houari-oran"], authorName: "Malika Brahimi", rating: 4, comment: "Bonne expérience traditionnelle. Ambiance conviviale, service agréable." },

    { listingId: listingMap["salon-oriental-tlemcen"], authorName: "Fatima Ziani", rating: 5, comment: "Salon historique de Tlemcen! La henna traditionnelle est magnifique, les designs sont uniques. Service exceptionnel!" },
    { listingId: listingMap["salon-oriental-tlemcen"], authorName: "Aicha Kara", rating: 5, comment: "Je viens ici depuis 10 ans. Rien n'a changé, toujours aussi professionnel et les traditions sont respectées." },

    { listingId: listingMap["laser-center-setif"], authorName: "Nassima Benaissa", rating: 5, comment: "Épilation laser très efficace. Après 6 séances, résultats parfaits sur les jambes. Personnel qualifié et machines récentes." },
    { listingId: listingMap["laser-center-setif"], authorName: "Hana Meddour", rating: 4, comment: "Bons résultats, équipe professionnelle. Prévoir plusieurs séances pour un résultat optimal." },

    { listingId: listingMap["studio-ongles-prestige-alger"], authorName: "Meriem Bencherif", rating: 5, comment: "Le meilleur nail studio d'Alger! Les designs sont créatifs, la qualité du gel est impeccable. Je reviens chaque mois!" },
    { listingId: listingMap["studio-ongles-prestige-alger"], authorName: "Roumaissa Dib", rating: 5, comment: "Mes ongles n'ont jamais été aussi beaux. Profesionnelle, rapide et très créative dans les designs. TOP!" },
    { listingId: listingMap["studio-ongles-prestige-alger"], authorName: "Wissam Belabbas", rating: 5, comment: "Venue pour un nail art berbère, résultat époustouflant! Très fidèle à ce studio depuis 2 ans." },

    { listingId: listingMap["centre-soins-corporels-yemma-bejaia"], authorName: "Tiziri Aït Ouali", rating: 5, comment: "Le massage aux huiles d'argan kabyle est magique! Personnel chaleureux, ambiance authentique. Bonne adresse à Béjaïa." },
    { listingId: listingMap["centre-soins-corporels-yemma-bejaia"], authorName: "Ouarda Moulai", rating: 5, comment: "Soin enveloppement argile excellent pour la peau. Je ressors toujours comme neuve. Je recommande à toutes!" },

    { listingId: listingMap["parfumerie-diaf-alger"], authorName: "Imane Belkacemi", rating: 5, comment: "La meilleure parfumerie d'Alger! Énorme choix, personnel très compétent. Les ouds sont authentiques et de qualité." },
    { listingId: listingMap["parfumerie-diaf-alger"], authorName: "Karima Sahraoui", rating: 4, comment: "Grand choix de parfums, bon service. Parfois un peu bondé mais les conseillères sont patientes et professionnelles." },
  ];

  await db.insert(reviewsTable).values(reviewsData);
  console.log(`✓ Seeded ${reviewsData.length} reviews`);

  console.log("\n✅ Database seeded successfully!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
